name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Install Eleventy globally
        run: npm install -g @11ty/eleventy

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Build Site
        run: npm run build
        
      - name: Deploy to Hosting Provider
        run: |
          lftp -u "u261657911.maple-ink.com,ftp:maple-1NK" -e "set ssl:verify-certificate no; mirror -R ./public /public_html/schiller; exit" ftp://femboy-heaven.com
