name: Build 11ty Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Eleventy Output Directory
        run: |
          mkdir -p public
          echo "module.exports = function() { return { dir: { input: 'src', output: 'public' } } };" > .eleventy.js

      - name: Install Dependencies
        run: npm install

      - name: Install Eleventy globally
        run: npm install -g @11ty/eleventy

      - name: Build Site
        run: npm run build
