name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Install Eleventy globally
        run: npm install -g @11ty/eleventy

      - name: Build Site
        run: npm run build

      - name: Deploy Site
        run: scp -r -P 65002 ./public/* u261657911:kysdAk-supwu1-vatgud@217.21.77.165:/public_html/schiller/
