name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Install Eleventy globally
        run: npm install -g @11ty/eleventy

      - name: Build Site
        run: npm run build
        
      - name: Deploy to Hosting Provider
        run: ssh -p 65002 u261657911:kysdAk-supwu1-vatgud@217.21.77.165 "cd /public_html/schiller/ && rm -rf *"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
